fos_rest:
    view:
        view_response_listener:  true
        formats:
            json: true
    format_listener:
        rules:
            - { path: ^/api/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    exception:
            codes:
                'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
                'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            messages:
                'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true