<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzjn2P4\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzjn2P4/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIzjn2P4.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIzjn2P4\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIzjn2P4\appAppKernelProdContainer([
    'container.build_hash' => 'Izjn2P4',
    'container.build_id' => 'd86295f6',
    'container.build_time' => 1680964917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzjn2P4');
