export const FETCH_ALL_LAST_OFFRES = 'FETCH_ALL_LAST_OFFRES';
export const LAST_OFFRES_ERROR = 'LAST_OFFRES_ERROR';
export const SET_LOADING_LAST_OFFRES = 'SET_LOADING_LAST_OFFRES';

export const FETCH_NAVLINKS = 'FETCH_NAVLINKS';
export const NAVLINKS_ERROR = 'NAVLINKS_ERROR';
export const SET_LOADING_NAVLINKS = 'SET_LOADING_NAVLINKS';

export const FETCH_HOMESLIDES = 'FETCH_HOMESLIDES';
export const HOMESLIDES_ERROR = 'HOMESLIDES_ERROR';
export const SET_LOADING_HOMESLIDES = 'SET_LOADING_HOMESLIDES';

export const FETCH_PARAMS_SITE = 'FETCH_PARAMS_SITE';
export const PARAMS_ERROR = 'PARAMS_ERROR';
export const SET_LOADING_PARAMS = 'SET_LOADING_PARAMS';

export const FETCH_ALL_LIST_FONCTION = 'FETCH_ALL_LIST_FONCTION';
export const LIST_FONCTION_ERROR = 'LIST_FONCTION_ERROR';
export const SET_LOADING_LIST_FONCTION = 'SET_LOADING_LIST_FONCTION';

export const FETCH_ALL_LIST_DEPARTEMENT = 'FETCH_ALL_LIST_DEPARTEMENT';
export const LIST_DEPARTEMENT_ERROR = 'LIST_DEPARTEMENT_ERROR';
export const SET_LOADING_LIST_DEPARTEMENT = 'SET_LOADING_LIST_DEPARTEMENT';

export const FETCH_ALL_LIST_NAVIGATION = 'FETCH_ALL_LIST_NAVIGATION';
export const LIST_NAVIGATION_ERROR = 'LIST_NAVIGATION_ERROR';
export const SET_LOADING_LIST_NAVIGATION = 'SET_LOADING_LIST_NAVIGATION';

export const FETCH_ALL_BLOCS_CMS = 'FETCH_ALL_BLOCS_CMS';
export const LIST_BLOCS_CMS_ERROR = 'LIST_BLOCS_CMS_ERROR';
export const SET_LOADING_BLOCS_CMS = 'SET_LOADING_BLOCS_CMS';

export const FETCH_ALL_ENTREPRISE = 'FETCH_ALL_ENTREPRISE';
export const ENTREPRISE_ERROR = 'ENTREPRISE_ERROR';
export const SET_LOADING_ENTREPRISE = 'SET_LOADING_ENTREPRISE';

export const FETCH_ALL_ACTU = "FETCH_ALL_ACTU";
export const ACTU_ERROR = "ACTU_ERROR";
export const SET_LOADING_ACTU = "SET_LOADING_ACTU";